---
openapi: 3.0.0
info:
  title: Personal Portfolio Configuration API
  version: '1.0'
paths:
  "/api/currencies":
    "$ref": './resources/currency/list.yml'
  "/api/currencies/{id}":
    "$ref": './resources/currency/single.yml'
  "/api/securities":
    "$ref": './resources/security/list.yml'
  "/api/securities/{id}":
    "$ref": './resources/security/single.yml'
components:
  schemas:
    Currency:
      "$ref": './types/currency.yml'
    Security:
      "$ref": './types/security.yml'